package main

import (
        "fmt"
        "net/http"
)

func main() {
        http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
                _, _ = fmt.Fprintf(w, "\t Wellcome to the main page! If you see this message it means that the page is working.\n\n This is web page, generated by Golang Application from Docker container, using HTTPS. \n\n Updated: 25.12.19")
        })

        http.HandleFunc("/hello/", func(w http.ResponseWriter, r *http.Request) {
                _, _ = fmt.Fprintf(w, "Hello World")
        })

	http.HandleFunc("/domain/", func(w http.ResponseWriter, r *http.Request) {
		_, _ = fmt.Fprintf(w, "Req: %s %s", r.Host, r.URL.Path)
	})

        fmt.Println("Start server")
        _ = http.ListenAndServe(":8001", nil)
}
